### ISSUE TITLE
Using yarn producess 'tsc-alias' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by RodrigoTomeES** [NikolaRHristov/TypeScriptESBuild#136]
Hi,

I have this script `"yarn lint && yarn tsc && yarn Build 'src/**/*.ts'"` to build my package [astro-rename](https://github.com/RodrigoTomeES/astro-rename/pull/17) and when I use yarn instead of npm doesn't find tsc-alias packages.

```bash
$ yarn run build

  Target\src\index.js    2.9kb
  Target\src\utils.js    951b
  Target\src\options.js  159b
  Target\src\types.js      0b

Done in 9ms

  Target/src/index.js ─── 2.9kb ─ 100.0%
   └ src/index.ts ─────── 2.9kb ── 99.3%

  Target/src/utils.js ─── 951b ── 100.0%
   └ src/utils.ts ─────── 801b ─── 84.2%

  Target/src/options.js ─ 159b ── 100.0%
   └ src/options.ts ───── 130b ─── 81.8%

  Target/src/types.js ───── 0b ── 100.0%

'tsc-alias' is not recognized as an internal or external command,
operable program or batch file.
```

Is it possible to solve it? Thanks!

**Comment by NikolaRHristov** [comment]
Heck, well `tsc-alias` gets executed via a "shell" prompt in a `child_process` in https://github.com/PlayForm/Build/blob/Current/Source/Function/Build.ts#L55 from https://github.com/PlayForm/Build/blob/bcbe1137a7867fdfcaa70327ded41c06fdcc60fd/Source/Function/Exec.ts#L9-L11 Can you maybe also try to add it as a dependency in your project as well ?

```sh
yarn install tsc-alias
# or however you install things with yarn 😁
```

**Comment by RodrigoTomeES** [comment]
Yeah, I already tried it but it also throw the error

**Comment by NikolaRHristov** [comment]
Damn, Ok. I will test it out with `yarn` and give you feedback.

**Comment by NikolaRHristov** [comment]
So, I'm trying it out on https://github.com/Nikolarhristov/DeveloperYarn with

`package.json` in https://github.com/PlayForm/Compress/blob/1bf7e08f7eab607a7931a6eba37199299ec10af8/package.json#L39

and it runs successfully.

Also it runs when I do it from the parent turborepo task in `package.json` https://github.com/NikolaRHristov/DeveloperYarn/blob/Current/package.json

I see that you're now using npx in https://github.com/RodrigoTomeES/astro-rename/blob/feature/v2/package.json

Are you still having this issue with `yarn` or just chose to switch to `npm`?

**Comment by RodrigoTomeES** [comment]
@NikolaRHristov I think you didn't have the issue because you used the v1 version instead of v4 (that I am using).

I changed to npm to avoid the error

**Comment by NikolaRHristov** [comment]
I was able to run it with `yarn` `v4.3.1` as well but glad you got it resolved by using `npm`.
